server:
  port: 8282

spring:
  # Database
  datasource:
    driverClassName: org.postgresql.Driver

    url: jdbc:postgresql://localhost:5432/relog
    username: postgres
    password: thiago30

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

security:
  jwt:
    secret: "ghk45jgherogho834go3h4g"
    issuer: "Main"
    ttlMillis: 608500

# JWT
#security.jwt.secret=ghk45jgherogho834go3h4g
#security.jwt.issuer=Main
#La sesion dura una semana
#security.jwt.ttlMillis=604800000
