server:
  port: 8282

spring:
  # Database
  datasource:
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/relog
    #username: postgres
    #password: thiago30

    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://babar.db.elephantsql.com:5432/rpnacxnc
    username: rpnacxnc
    password: ScCc0PwPKCb1EO6YSc5e01w2BqKYA2gj

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop

security:
  jwt:
    secret: "ghk45jgherogho834go3h4g"
    issuer: "Main"
    ttlMillis: 604800000

# JWT
#security.jwt.secret=ghk45jgherogho834go3h4g
#security.jwt.issuer=Main
#La sesion dura una semana
#security.jwt.ttlMillis=604800000
#horas * 3600000
